version: '3'
services:
  web:
    image: crypto-docker
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

  
  redis:
    image: "redis:alpine"
